export const componentCatalogCategories = [
  { id: "global", label: "全局组件", path: "src/components/" },
  { id: "ui", label: "基础 UI", path: "src/components/ui/" },
  { id: "workbench", label: "AI 工作台", path: "src/components/workbench/" },
]

export const componentCatalog = [
  {
    id: "layout-client",
    name: "LayoutClient",
    category: "global",
    path: "src/components/LayoutClient.jsx",
    description: "全局页面布局容器，组合顶部栏、侧栏、主内容区和响应式状态。",
    usage: ["全平台路由"],
    status: "基础设施",
    preview: "layout",
  },
  {
    id: "topbar",
    name: "Topbar",
    category: "global",
    path: "src/components/Topbar.jsx",
    description: "平台品牌、一级导航、UI 规范、积分和用户入口。",
    usage: ["全平台顶部导航"],
    status: "稳定",
    preview: "topbar",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    category: "global",
    path: "src/components/Sidebar.jsx",
    description: "工具与管理模块侧栏，负责分组展开、选中态和移动端抽屉。",
    usage: ["全平台侧栏"],
    status: "稳定",
    preview: "sidebar",
  },
  {
    id: "page-shell",
    name: "PageShell",
    category: "global",
    path: "src/components/PageShell.jsx",
    description: "普通子页面的标题、面包屑、状态、操作区和内容外壳。",
    usage: ["素材库", "提示词库", "权限管理", "历史记录"],
    status: "稳定",
    preview: "page-shell",
  },
  {
    id: "page-header",
    name: "PageHeader",
    category: "global",
    path: "src/components/PageHeader.jsx",
    description: "旧版或非工作流页面的返回、面包屑和状态头部。",
    usage: ["非工作流子页面"],
    status: "兼容",
    preview: "page-header",
  },
  {
    id: "placeholder-state",
    name: "PlaceholderState",
    category: "global",
    path: "src/components/PlaceholderState.jsx",
    description: "规划中或原型页面的统一占位状态。",
    usage: ["未完成页面"],
    status: "稳定",
    preview: "placeholder",
  },
  {
    id: "safe-image",
    name: "SafeImage",
    category: "global",
    path: "src/components/SafeImage.jsx",
    description: "图片加载失败时安全隐藏，避免页面渲染中断。",
    usage: ["图片卡片", "任务结果", "弹窗预览"],
    status: "稳定",
    preview: "safe-image",
  },
  {
    id: "button",
    name: "Button",
    category: "ui",
    path: "src/components/ui/button.jsx",
    description: "shadcn/Base UI 按钮原语，支持默认、描边、次级、幽灵、危险和链接变体。",
    usage: ["表单", "弹窗", "管理页"],
    status: "稳定",
    preview: "button",
  },
  {
    id: "avatar",
    name: "Avatar",
    category: "ui",
    path: "src/components/ui/avatar.jsx",
    description: "头像、回退文字、状态角标和头像组。",
    usage: ["用户入口", "人员列表"],
    status: "稳定",
    preview: "avatar",
  },
  {
    id: "dropdown-menu",
    name: "DropdownMenu",
    category: "ui",
    path: "src/components/ui/dropdown-menu.jsx",
    description: "下拉菜单原语家族，包含普通项、勾选项、单选项和子菜单。",
    usage: ["用户菜单", "列表操作"],
    status: "稳定",
    preview: "dropdown",
  },
  {
    id: "workbench-family",
    name: "Workbench 页面骨架",
    category: "workbench",
    path: "src/components/workbench/Workbench.jsx",
    description: "AI 工作台页面母版家族，包含 Shell、Topline、Panel、Scroll、Footer、Module、Button 和 Empty。",
    usage: ["专家模式", "AI 买家秀", "AI 商品套图"],
    status: "稳定",
    preview: "workbench",
  },
  {
    id: "workbench-controls",
    name: "WorkbenchControls",
    category: "workbench",
    path: "src/components/workbench/WorkbenchControls.jsx",
    description: "工作台模型选择、参数组合选择、Toast 和图标按钮。",
    usage: ["专家模式", "AI 买家秀", "AI 商品套图"],
    status: "稳定",
    preview: "controls",
  },
  {
    id: "workbench-picker-dialog",
    name: "WorkbenchPickerDialog",
    category: "workbench",
    path: "src/components/workbench/WorkbenchPickerDialog.jsx",
    description: "大型选择弹窗母版，统一 Portal、焦点循环、Esc、遮罩关闭和固定头尾。",
    usage: ["素材选择器", "提示词选择器"],
    status: "稳定",
    preview: "picker-base",
  },
  {
    id: "asset-picker-modal",
    name: "AssetPickerModal",
    category: "workbench",
    path: "src/components/workbench/AssetPickerModal.jsx",
    description: "从个人、团体、公共素材和本地文件选择图片。",
    usage: ["专家模式", "AI 买家秀", "AI 商品套图"],
    status: "稳定",
    preview: "asset-picker",
  },
  {
    id: "prompt-picker-modal",
    name: "PromptPickerModal",
    category: "workbench",
    path: "src/components/workbench/PromptPickerModal.jsx",
    description: "从个人、团队、公共提示词和灵感广场选择模板。",
    usage: ["专家模式", "AI 买家秀"],
    status: "稳定",
    preview: "prompt-picker",
  },
  {
    id: "image-queue-module",
    name: "ImageQueueModule",
    category: "workbench",
    path: "src/components/workbench/ImageQueueModule.jsx",
    description: "参考图片队列，统一素材选择、本地上传、排序、预览、替换和删除。",
    usage: ["专家模式", "AI 买家秀", "AI 商品套图"],
    status: "稳定",
    preview: "image-queue",
  },
  {
    id: "image-preview-modal",
    name: "ImagePreviewModal",
    category: "workbench",
    path: "src/components/workbench/ImagePreviewModal.jsx",
    description: "图片大图预览，支持切换、缩放、拖动、翻转、下载和吸色。",
    usage: ["图片队列", "结果预览"],
    status: "稳定",
    preview: "image-preview",
  },
  {
    id: "region-mask-editor",
    name: "RegionMaskEditor",
    category: "workbench",
    path: "src/components/workbench/RegionMaskEditor.jsx",
    description: "图片区域编辑、遮罩、擦除、撤销、重做与文本标注。",
    usage: ["专家模式", "AI 买家秀"],
    status: "业务特化",
    preview: "region-editor",
  },
  {
    id: "color-constraint-picker",
    name: "ColorConstraintPicker",
    category: "workbench",
    path: "src/components/workbench/ColorConstraintPicker.jsx",
    description: "公共吸色入口和颜色约束标签，支持 HEX 复制与删除。",
    usage: ["AI 买家秀", "图片预览"],
    status: "稳定",
    preview: "colors",
  },
  {
    id: "workbench-text-editor",
    name: "WorkbenchTextEditor",
    category: "workbench",
    path: "src/components/workbench/WorkbenchTextEditor.jsx",
    description: "工作台通用创作文案输入，统一字数、清空、工具栏和业务扩展区。",
    usage: ["AI 商品套图", "后续工作台"],
    status: "稳定",
    preview: "text-editor",
  },
  {
    id: "workbench-prompt-editor",
    name: "WorkbenchPromptEditor",
    category: "workbench",
    path: "src/components/workbench/WorkbenchPromptEditor.jsx",
    description: "基于通用编辑器封装提示词模板和 AI 润色。",
    usage: ["专家模式", "AI 买家秀"],
    status: "稳定",
    preview: "prompt-editor",
  },
  {
    id: "workbench-recent-history",
    name: "WorkbenchRecentHistory",
    category: "workbench",
    path: "src/components/workbench/WorkbenchRecentHistory.jsx",
    description: "工作台最近三天历史窄栏，支持刷新、复制提示词、继续编辑和跳转完整历史。",
    usage: ["专家模式", "主体替换", "产品微调", "批量美颜", "后续生成工作台"],
    status: "稳定",
    preview: "recent-history",
  },
]
